### ISSUE TITLE
YaneuraOu minimal hardware requirements and evaluation files

### ISSUE THREAD

**Issue by ChessGUI** [yaneurao/YaneuraOu#10]
Hello yaneurao!

Someone said: "YaneuraOu also cannot run without evaluation parameters, which have to be downloaded from another Google Drive. Unfortunately the zip file is 5.7GB. This might take me several hours. I dread to see how large it will get when I unzip it. As the evaluation parameters probably have to be in memory, it is likely that YaneuraOu cannot run on a machine with less than 16GB RAM. My biggest machine has 8GB."

Well I own a desktop computer with Windows 7 SP1 64 bit and the following components:

Intel Core i5 3470 @ 3.20GHz Ivy Bridge 22nm Technology> .bmi2.executables are not supported
4,00GB RAM  Dual-Channel DDR3 @ 798MHz (11-11-11-28)
Motherboard ASRock H61M-DGS R2.0 (CPUSocket)

Where can be found the exact download link of the evaluation parameters on Google Drive? Has this connection a torrent-file for the download procedure?  I cannot find these necessary informations.
Are 5,7 GB data volume indeed required to run YaneuraOu with a GUI respectively it is possible for you to develop Yaneura Ou program without evaluation parameters like other USI engines?

WinBoard 4.8.0 graphical interface is able to use USI compatible engines cf. http://home.hccnet.nl/h.g.muller/shokidoki.html and
http://www.open-aurec.com/wbforum/viewtopic.php?f=19&t=51528 plays normal chess , Japanese / Chinese and many other variants.

**Comment by woodyring** [comment]
Hi ChessGUI,

I think "someone" misunderstand. (I think google's Japanese translation is bad for any languages)
The 5.7GB file is for creating newer evaluation parameters by machine learning ( like as SGD ).
So you do NOT need to download it.

YaneuraOu supports some evaluation parameter types. And currently, YaneuraOu (2016 Mid engine) uses Apery's evaluation parameters. Apery is also CSI shogi engine.

Apery's evaluation parameter needs 1.2GB RAM.
So your PC can run YaneuraOu. But you should use YaneuraOu-2016-mid-sse42.exe because of AVX2.

You can setup YaneuraOu as followings

1. Donwload YaneuraOu from github, and extract it.
2. Download Apery WCSC26.
  https://github.com/HiraokaTakuya/apery/releases/download/WCSC26/apery_wcsc26.zip
    (You can register Apery, too)
3. Extract a zip file and copy three K*_synthesized.bin files into YaneuraOu's eval directory.
   (Run YaneuraOu-2016-mid-sse42.exe by double-click, and type "bench" USI command for test.)
4. Register YaneuraOu-2016-mid-sse42.exe to GUI.

You can use another CSI engine named Gikou.
https://github.com/gikou-official/Gikou
https://github.com/gikou-official/Gikou/releases/download/v1.0.1/gikou_win_20160606.zip

Have fun. :-)

**Comment by yaneurao** [comment]
I thank woodring for your help.
Enjoy shogi! > ChessGUI
