### ISSUE TITLE
Feature request: tsume shogi support

### ISSUE THREAD

**Issue by orclstefan** [yaneurao/YaneuraOu#107]
Hi Yaneurao, 

just wanted to quickly ask if there are any plans for supporting tsume shogi with this engine? Right now if you set a tsume position the app just crashes.

for example this:
position sfen 7nl/9/5S1kp/6R1s/9/7p1/9/9/9 b Gr2b3g2s3n3l16p

Regards,
Stefan

**Comment by yaneurao** [comment]
Please use tanuki- mate engine for a tsume shogi.

How to build tanuki- mate engine : 
$ make -j8 tournament TARGET_CPU=AVX2 COMPILER=g++ YANEURAOU_EDITION=MATE_ENGINE ENGINE_NAME="tanuki- mate engine"

I have no plan to support tsume shogi in YANEURAOU_ENGINE_NNUE/KPPT , because a tsume shogi engine and a normal engine have significant differences in many points.

**Comment by orclstefan** [comment]
Thank you for the very quick reply! - I am not really looking for a mating engine, i already know the tsume solution, i am looking for something that can i can play tsume against - with me playing as sente, attacking & trying to solve the tsume puzzle and the Yaneuraou engine is playing as gote, trying to evade and avoid being mated. 

I noticed the original Apery engine does support it, so i might have to use that engine. Good luck with your project, looking forward to see how well you do in this years World Computer Shogi Championship ;-)!
